import type { Theme } from "./types"

export const themes: Record<"herval" | "taqi" | "iplace", Theme> = {
    herval: {
        light: {
            background: "#ffffff",
            foreground: "#0a0a0a",
            card: "#ffffff",
            "card-foreground": "#0a0a0a",
            popover: "#ffffff",
            "popover-foreground": "#0a0a0a",
            primary: "#E10000",
            "primary-foreground": "#ffffff",
            secondary: "#f5f5f5",
            "secondary-foreground": "#171717",
            muted: "#f5f5f5",
            "muted-foreground": "#737373",
            accent: "#fff5f5",
            "accent-foreground": "#b91c1c",
            destructive: "#dc2626",
            "destructive-foreground": "#ffffff",
            border: "#e5e5e5",
            input: "#e5e5e5",
            ring: "#E10000",
            sidebar: "oklch(0.985 0 0)",
            "sidebar-foreground": "oklch(0.145 0 0)",
            "sidebar-primary": "oklch(0.205 0 0)",
            "sidebar-primary-foreground": "oklch(0.985 0 0)",
            "sidebar-accent": "oklch(0.97 0 0)",
            "sidebar-accent-foreground": "oklch(0.205 0 0)",
            "sidebar-border": "oklch(0.922 0 0)",
            "sidebar-ring": "oklch(0.708 0 0)",
        },
        dark: {
            background: "#0a0a0a",
            foreground: "#fafafa",
            card: "#0a0a0a",
            "card-foreground": "#fafafa",
            popover: "#0a0a0a",
            "popover-foreground": "#fafafa",
            primary: "#E10000",
            "primary-foreground": "#ffffff",
            secondary: "#262626",
            "secondary-foreground": "#fafafa",
            muted: "#262626",
            "muted-foreground": "#a3a3a3",
            accent: "#450a0a",
            "accent-foreground": "#fca5a5",
            destructive: "#7f1d1d",
            "destructive-foreground": "#fafafa",
            border: "#262626",
            input: "#262626",
            ring: "#ff4444",
            sidebar: "oklch(0.205 0 0)",
            "sidebar-foreground": "oklch(0.985 0 0)",
            "sidebar-primary": "oklch(0.488 0.243 264.376)",
            "sidebar-primary-foreground": "oklch(0.985 0 0)",
            "sidebar-accent": "oklch(0.269 0 0)",
            "sidebar-accent-foreground": "oklch(0.985 0 0)",
            "sidebar-border": "oklch(1 0 0 / 10%)",
            "sidebar-ring": "oklch(0.439 0 0)",
        },
    },
    taqi: {
        light: {
            background: "#ffffff",
            foreground: "#0a0a0a",
            card: "#ffffff",
            "card-foreground": "#0a0a0a",
            popover: "#ffffff",
            "popover-foreground": "#0a0a0a",
            primary: "#eb5c2e",
            "primary-foreground": "#ffffff",
            secondary: "#f5f5f5",
            "secondary-foreground": "#171717",
            muted: "#f5f5f5",
            "muted-foreground": "#737373",
            accent: "#fff7ed",
            "accent-foreground": "#c2410c",
            destructive: "#dc2626",
            "destructive-foreground": "#ffffff",
            border: "#e5e5e5",
            input: "#e5e5e5",
            ring: "#eb5c2e",
            sidebar: "oklch(0.985 0 0)",
            "sidebar-foreground": "oklch(0.145 0 0)",
            "sidebar-primary": "oklch(0.205 0 0)",
            "sidebar-primary-foreground": "oklch(0.985 0 0)",
            "sidebar-accent": "oklch(0.97 0 0)",
            "sidebar-accent-foreground": "oklch(0.205 0 0)",
            "sidebar-border": "oklch(0.922 0 0)",
            "sidebar-ring": "oklch(0.708 0 0)",
        },
        dark: {
            background: "#0a0a0a",
            foreground: "#fafafa",
            card: "#0a0a0a",
            "card-foreground": "#fafafa",
            popover: "#0a0a0a",
            "popover-foreground": "#fafafa",
            primary: "#eb5c2e",
            "primary-foreground": "#ffffff",
            secondary: "#262626",
            "secondary-foreground": "#fafafa",
            muted: "#262626",
            "muted-foreground": "#a3a3a3",
            accent: "#431407",
            "accent-foreground": "#fdba74",
            destructive: "#7f1d1d",
            "destructive-foreground": "#fafafa",
            border: "#262626",
            input: "#262626",
            ring: "#fb923c",
            sidebar: "oklch(0.205 0 0)",
            "sidebar-foreground": "oklch(0.985 0 0)",
            "sidebar-primary": "oklch(0.488 0.243 264.376)",
            "sidebar-primary-foreground": "oklch(0.985 0 0)",
            "sidebar-accent": "oklch(0.269 0 0)",
            "sidebar-accent-foreground": "oklch(0.985 0 0)",
            "sidebar-border": "oklch(1 0 0 / 10%)",
            "sidebar-ring": "oklch(0.439 0 0)",
        },
    },
    iplace: {
        light: {
            background: "#ffffff",
            foreground: "#0a0a0a",
            card: "#ffffff",
            "card-foreground": "#0a0a0a",
            popover: "#ffffff",
            "popover-foreground": "#0a0a0a",
            primary: "#c6d30d",
            "primary-foreground": "#1a1a0a",
            secondary: "#f5f5f5",
            "secondary-foreground": "#171717",
            muted: "#f5f5f5",
            "muted-foreground": "#737373",
            accent: "#fefce8",
            "accent-foreground": "#854d0e",
            destructive: "#dc2626",
            "destructive-foreground": "#ffffff",
            border: "#e5e5e5",
            input: "#e5e5e5",
            ring: "#c6d30d",
            sidebar: "oklch(0.985 0 0)",
            "sidebar-foreground": "oklch(0.145 0 0)",
            "sidebar-primary": "oklch(0.205 0 0)",
            "sidebar-primary-foreground": "oklch(0.985 0 0)",
            "sidebar-accent": "oklch(0.97 0 0)",
            "sidebar-accent-foreground": "oklch(0.205 0 0)",
            "sidebar-border": "oklch(0.922 0 0)",
            "sidebar-ring": "oklch(0.708 0 0)",
        },
        dark: {
            background: "#0a0a0a",
            foreground: "#fafafa",
            card: "#0a0a0a",
            "card-foreground": "#fafafa",
            popover: "#0a0a0a",
            "popover-foreground": "#fafafa",
            primary: "#c6d30d",
            "primary-foreground": "#1a1a0a",
            secondary: "#262626",
            "secondary-foreground": "#fafafa",
            muted: "#262626",
            "muted-foreground": "#a3a3a3",
            accent: "#3f3f0a",
            "accent-foreground": "#fde047",
            destructive: "#7f1d1d",
            "destructive-foreground": "#fafafa",
            border: "#262626",
            input: "#262626",
            ring: "#d4e157",
            sidebar: "oklch(0.205 0 0)",
            "sidebar-foreground": "oklch(0.985 0 0)",
            "sidebar-primary": "oklch(0.488 0.243 264.376)",
            "sidebar-primary-foreground": "oklch(0.985 0 0)",
            "sidebar-accent": "oklch(0.269 0 0)",
            "sidebar-accent-foreground": "oklch(0.985 0 0)",
            "sidebar-border": "oklch(1 0 0 / 10%)",
            "sidebar-ring": "oklch(0.439 0 0)",
        },
    },
}

export function getTheme(color: "herval" | "taqi" | "iplace") {
    return themes[color]
}
