import type { Theme } from "./types"

export const themes: Record<"red" | "orange" | "green", Theme> = {
    red: {
        light: {
            background: "#ffffff",
            foreground: "#0a0a0a",
            card: "#ffffff",
            "card-foreground": "#0a0a0a",
            popover: "#ffffff",
            "popover-foreground": "#0a0a0a",
            primary: "#dc2626", // red-600
            "primary-foreground": "#ffffff",
            secondary: "#f5f5f5",
            "secondary-foreground": "#171717",
            muted: "#f5f5f5",
            "muted-foreground": "#737373",
            accent: "#fef2f2", // red-50
            "accent-foreground": "#991b1b", // red-800
            destructive: "#dc2626",
            "destructive-foreground": "#ffffff",
            border: "#e5e5e5",
            input: "#e5e5e5",
            ring: "#dc2626",
            sidebar: "oklch(0.985 0 0)",
            "sidebar-foreground": "oklch(0.145 0 0)",
            "sidebar-primary": "oklch(0.205 0 0)",
            "sidebar-primary-foreground": "oklch(0.985 0 0)",
            "sidebar-accent": "oklch(0.97 0 0)",
            "sidebar-accent-foreground": "oklch(0.205 0 0)",
            "sidebar-border": "oklch(0.922 0 0)",
            "sidebar-ring": "oklch(0.708 0 0)",
        },
        dark: {
            background: "#0a0a0a",
            foreground: "#fafafa",
            card: "#0a0a0a",
            "card-foreground": "#fafafa",
            popover: "#0a0a0a",
            "popover-foreground": "#fafafa",
            primary: "#c70000", // red-500
            "primary-foreground": "#ffffff",
            secondary: "#262626",
            "secondary-foreground": "#fafafa",
            muted: "#262626",
            "muted-foreground": "#a3a3a3",
            accent: "#450a0a", // red-950
            "accent-foreground": "#fca5a5", // red-300
            destructive: "#7f1d1d",
            "destructive-foreground": "#fafafa",
            border: "#262626",
            input: "#262626",
            ring: "#ef4444",
            sidebar: "oklch(0.205 0 0)",
            "sidebar-foreground": "oklch(0.985 0 0)",
            "sidebar-primary": "oklch(0.488 0.243 264.376)",
            "sidebar-primary-foreground": "oklch(0.985 0 0)",
            "sidebar-accent": "oklch(0.269 0 0)",
            "sidebar-accent-foreground": "oklch(0.985 0 0)",
            "sidebar-border": "oklch(1 0 0 / 10%)",
            "sidebar-ring": "oklch(0.439 0 0)",
        },
    },
    orange: {
        light: {
            background: "#ffffff",
            foreground: "#0a0a0a",
            card: "#ffffff",
            "card-foreground": "#0a0a0a",
            popover: "#ffffff",
            "popover-foreground": "#0a0a0a",
            primary: "#ea580c", // orange-600
            "primary-foreground": "#ffffff",
            secondary: "#f5f5f5",
            "secondary-foreground": "#171717",
            muted: "#f5f5f5",
            "muted-foreground": "#737373",
            accent: "#fff7ed", // orange-50
            "accent-foreground": "#9a3412", // orange-800
            destructive: "#dc2626",
            "destructive-foreground": "#ffffff",
            border: "#e5e5e5",
            input: "#e5e5e5",
            ring: "#ea580c",
            sidebar: "oklch(0.985 0 0)",
            "sidebar-foreground": "oklch(0.145 0 0)",
            "sidebar-primary": "oklch(0.205 0 0)",
            "sidebar-primary-foreground": "oklch(0.985 0 0)",
            "sidebar-accent": "oklch(0.97 0 0)",
            "sidebar-accent-foreground": "oklch(0.205 0 0)",
            "sidebar-border": "oklch(0.922 0 0)",
            "sidebar-ring": "oklch(0.708 0 0)",
        },
        dark: {
            background: "#0a0a0a",
            foreground: "#fafafa",
            card: "#0a0a0a",
            "card-foreground": "#fafafa",
            popover: "#0a0a0a",
            "popover-foreground": "#fafafa",
            primary: "#f97316", // orange-500
            "primary-foreground": "#ffffff",
            secondary: "#262626",
            "secondary-foreground": "#fafafa",
            muted: "#262626",
            "muted-foreground": "#a3a3a3",
            accent: "#431407", // orange-950
            "accent-foreground": "#fdba74", // orange-300
            destructive: "#7f1d1d",
            "destructive-foreground": "#fafafa",
            border: "#262626",
            input: "#262626",
            ring: "#f97316",
            sidebar: "oklch(0.205 0 0)",
            "sidebar-foreground": "oklch(0.985 0 0)",
            "sidebar-primary": "oklch(0.488 0.243 264.376)",
            "sidebar-primary-foreground": "oklch(0.985 0 0)",
            "sidebar-accent": "oklch(0.269 0 0)",
            "sidebar-accent-foreground": "oklch(0.985 0 0)",
            "sidebar-border": "oklch(1 0 0 / 10%)",
            "sidebar-ring": "oklch(0.439 0 0)",
        },
    },
    green: {
        light: {
            background: "#ffffff",
            foreground: "#0a0a0a",
            card: "#ffffff",
            "card-foreground": "#0a0a0a",
            popover: "#ffffff",
            "popover-foreground": "#0a0a0a",
            primary: "#16a34a", // green-600
            "primary-foreground": "#ffffff",
            secondary: "#f5f5f5",
            "secondary-foreground": "#171717",
            muted: "#f5f5f5",
            "muted-foreground": "#737373",
            accent: "#f0fdf4", // green-50
            "accent-foreground": "#166534", // green-800
            destructive: "#dc2626",
            "destructive-foreground": "#ffffff",
            border: "#e5e5e5",
            input: "#e5e5e5",
            ring: "#16a34a",
            sidebar: "oklch(0.985 0 0)",
            "sidebar-foreground": "oklch(0.145 0 0)",
            "sidebar-primary": "oklch(0.205 0 0)",
            "sidebar-primary-foreground": "oklch(0.985 0 0)",
            "sidebar-accent": "oklch(0.97 0 0)",
            "sidebar-accent-foreground": "oklch(0.205 0 0)",
            "sidebar-border": "oklch(0.922 0 0)",
            "sidebar-ring": "oklch(0.708 0 0)",
        },
        dark: {
            background: "#0a0a0a",
            foreground: "#fafafa",
            card: "#0a0a0a",
            "card-foreground": "#fafafa",
            popover: "#0a0a0a",
            "popover-foreground": "#fafafa",
            primary: "#22c55e", // green-500
            "primary-foreground": "#ffffff",
            secondary: "#262626",
            "secondary-foreground": "#fafafa",
            muted: "#262626",
            "muted-foreground": "#a3a3a3",
            accent: "#052e16", // green-950
            "accent-foreground": "#86efac", // green-300
            destructive: "#7f1d1d",
            "destructive-foreground": "#fafafa",
            border: "#262626",
            input: "#262626",
            ring: "#22c55e",
            sidebar: "oklch(0.205 0 0)",
            "sidebar-foreground": "oklch(0.985 0 0)",
            "sidebar-primary": "oklch(0.488 0.243 264.376)",
            "sidebar-primary-foreground": "oklch(0.985 0 0)",
            "sidebar-accent": "oklch(0.269 0 0)",
            "sidebar-accent-foreground": "oklch(0.985 0 0)",
            "sidebar-border": "oklch(1 0 0 / 10%)",
            "sidebar-ring": "oklch(0.439 0 0)",
        },
    },
}

export function getTheme(color: "red" | "orange" | "green") {
    return themes[color]
}
